// Indicator registry with comprehensive metadata
// Each indicator is self-documenting with explicit keys

const INDICATORS_DATA = {
	// === Moving Averages ===
	sma: {
		name: 'SMA',
		category: 'movingAverages',
		description: 'Simple Moving Average',
		longDescription: 'Period=20/50/200. Price>SMA=uptrend.',
		defaultConfig: { period: 20 },
		warmup: (c) => c.period,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'SMA_20',
			subcategory: 'trend_following',
			signal_type: 'trend',
			lag: 'medium',
			best_for: ['trending', 'support_resistance'],
			correlation_group: 'moving_averages',
			complementary_with: ['RSI_14', 'MACD_12_26_9', 'ADX_14'],
			conflicts_with: ['EMA_26', 'WMA_20', 'DEMA_20'],
		},
	},
	ema: {
		name: 'EMA',
		category: 'movingAverages',
		description: 'Exponential Moving Average',
		longDescription: '12=fast, 26=slow. EMA12/26 cross=golden/death cross.',
		defaultConfig: { period: 26 },
		warmup: (c) => c.period * 2,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'EMA_26',
			subcategory: 'trend_following',
			signal_type: 'trend',
			lag: 'low',
			best_for: ['trending', 'crossover', 'dynamic_support_resistance'],
			correlation_group: 'moving_averages',
			complementary_with: ['RSI_14', 'MACD_12_26_9', 'ADX_14'],
			conflicts_with: ['SMA_20', 'WMA_20', 'DEMA_20'],
		},
	},
	wma: {
		name: 'WMA',
		category: 'movingAverages',
		description: 'Weighted Moving Average',
		longDescription: 'Reactive, less lag. Period=20.',
		defaultConfig: { period: 20 },
		warmup: (c) => c.period,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'WMA_20',
			subcategory: 'trend_following',
			signal_type: 'trend',
			lag: 'low',
			best_for: ['trending', 'recent_price_emphasis'],
			correlation_group: 'moving_averages',
			complementary_with: ['RSI_14', 'ADX_14'],
			conflicts_with: ['SMA_20', 'EMA_26', 'DEMA_20'],
		},
	},
	wsma: {
		name: 'WSMA',
		category: 'movingAverages',
		description: 'Smoothed Weighted Moving Average',
		longDescription: 'Double smoothing, fewer signals. Period=20.',
		defaultConfig: { period: 20 },
		warmup: (c) => c.period,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'WSMA_20',
			subcategory: 'trend_following',
			signal_type: 'trend',
			lag: 'medium',
			best_for: ['trending', 'noise_reduction'],
			correlation_group: 'moving_averages',
			complementary_with: ['ADX_14', 'MACD_12_26_9'],
			conflicts_with: ['SMA_20', 'EMA_26', 'WMA_20'],
		},
	},
	dema: {
		name: 'DEMA',
		category: 'movingAverages',
		description: 'Double Exponential Moving Average',
		longDescription: 'Reduced lag, fast reversals. Period=20.',
		defaultConfig: { period: 20 },
		warmup: (c) => c.period * 2,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'DEMA_20',
			subcategory: 'trend_following',
			signal_type: 'trend',
			lag: 'low',
			best_for: ['trending', 'fast_reversals'],
			correlation_group: 'moving_averages',
			complementary_with: ['RSI_14', 'MACD_12_26_9'],
			conflicts_with: ['EMA_26', 'WMA_20', 'SMA_20'],
		},
	},
	rma: {
		name: 'RMA',
		category: 'movingAverages',
		description: 'Wilder\'s Moving Average',
		longDescription: 'Used in RSI/ATR. Stable. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => c.period,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'RMA_14',
			subcategory: 'smoothed',
			signal_type: 'trend',
			lag: 'high',
			best_for: ['trending', 'smoothing'],
			correlation_group: 'moving_averages',
			complementary_with: ['RSI_14', 'ATR_14'],
			conflicts_with: ['SMA_20', 'EMA_26'],
		},
	},
	dma: {
		name: 'DMA',
		category: 'movingAverages',
		description: 'Displaced Moving Average',
		longDescription: 'Time-shifted, short/long components. Cross=trend signal.',
		defaultConfig: { short: 20, long: 50 },
		warmup: (c) => Math.max(c.short || 20, c.long || 50),
		type: 'composite',
		parametrable: true,
		components: ['short', 'long'],
		metadata: {
			id: 'DMA_20_50',
			subcategory: 'displaced',
			signal_type: 'trend',
			lag: 'medium',
			best_for: ['trending', 'crossover'],
			correlation_group: 'moving_averages',
			complementary_with: ['RSI_14', 'MACD_12_26_9'],
			conflicts_with: [],
		},
	},
	sma15: {
		name: 'Spencer\'s MA',
		category: 'movingAverages',
		description: 'Spencer 15-Period Moving Average',
		longDescription: 'Polynomial smoothing, low noise.',
		defaultConfig: {},
		warmup: () => 15,
		type: 'numeric',
		parametrable: false,
		components: null,
		metadata: {
			id: 'SPENCER_15',
			subcategory: 'polynomial',
			signal_type: 'trend',
			lag: 'medium',
			best_for: ['trending', 'noise_reduction'],
			correlation_group: 'moving_averages',
			complementary_with: ['ADX_14'],
			conflicts_with: ['SMA_20'],
		},
	},

	// === Momentum ===
	rsi: {
		name: 'RSI',
		category: 'momentum',
		description: 'Relative Strength Index',
		longDescription: '0-100 scale. >70 overbought, <30 oversold. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => (c.period || 14) + 1,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'RSI_14',
			subcategory: 'oscillator_bounded',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['ranging', 'overbought_oversold', 'divergence'],
			correlation_group: 'momentum_oscillators',
			complementary_with: ['EMA_26', 'VWAP', 'VOLUME', 'BB_20_2'],
			conflicts_with: [],
		},
	},
	macd: {
		name: 'MACD',
		category: 'momentum',
		description: 'Moving Average Convergence Divergence',
		longDescription: 'EMA fast-slow. Components: macd/signal/histogram. fast=12, slow=26, signal=9.',
		defaultConfig: { fast: 12, slow: 26, signal: 9 },
		warmup: (c) => (c.slow || 26) + (c.signal || 9) * 2,
		type: 'composite',
		parametrable: true,
		components: ['macd', 'signal', 'histogram'],
		metadata: {
			id: 'MACD_12_26_9',
			subcategory: 'oscillator_unbounded',
			signal_type: 'trend',
			lag: 'medium',
			best_for: ['trending', 'crossover', 'divergence'],
			correlation_group: 'momentum_trend',
			complementary_with: ['ADX_14', 'RSI_14', 'VOLUME', 'EMA_26'],
			conflicts_with: ['AO', 'MOM_10'],
		},
	},
	stochastic: {
		name: 'Stochastic',
		category: 'momentum',
		description: 'Stochastic Oscillator',
		longDescription: '%K/%D lines. k=14, d=3. >80 overbought, <20 oversold. %K/%D cross=confirmation.',
		defaultConfig: { k: 14, d: 3 },
		warmup: (c) => (c.k || 14) + (c.d || 3),
		type: 'composite',
		parametrable: true,
		components: ['stochK', 'stochD'],
		metadata: {
			id: 'STOCH_14_3',
			subcategory: 'oscillator_bounded',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['ranging', 'overbought_oversold', 'crossover'],
			correlation_group: 'momentum_oscillators',
			complementary_with: ['EMA_26', 'VOLUME', 'BB_20_2'],
			conflicts_with: ['STOCH_RSI_14_3_3'],
		},
	},
	stochRsi: {
		name: 'Stoch RSI',
		category: 'momentum',
		description: 'Stochastic of RSI',
		longDescription: 'Ultra-sensitive 0-100 scale. %K/%D. period=14, k=3, d=3. >80/<20 extremes.',
		defaultConfig: { period: 14, k: 3, d: 3 },
		warmup: (c) => (c.period || 14) * 10, // Increased warmup significantly for StochRSI
		type: 'composite',
		parametrable: true,
		components: ['stochRSI', 'stochRSISignal'],
		metadata: {
			id: 'STOCH_RSI_14_3_3',
			subcategory: 'oscillator_bounded',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['ranging', 'overbought_oversold', 'early_signals'],
			correlation_group: 'momentum_oscillators',
			complementary_with: ['EMA_26', 'VOLUME'],
			conflicts_with: ['STOCH_14_3'],
		},
	},
	williamsR: {
		name: 'Williams %R',
		category: 'momentum',
		description: 'Williams Percent Range',
		longDescription: '>-20 overbought, <-80 oversold. Fast. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => c.period || 14,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'WILLIAMS_R_14',
			subcategory: 'oscillator_bounded',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['ranging', 'overbought_oversold'],
			correlation_group: 'momentum_oscillators',
			complementary_with: ['EMA_26', 'VOLUME'],
			conflicts_with: [],
		},
	},
	cci: {
		name: 'CCI',
		category: 'momentum',
		description: 'Commodity Channel Index',
		longDescription: '>+100 overbought, <-100 oversold. No limits. Period=20.',
		defaultConfig: { period: 20 },
		warmup: (c) => c.period || 20,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'CCI_20',
			subcategory: 'oscillator_unbounded',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['ranging', 'overbought_oversold', 'extreme_moves'],
			correlation_group: 'momentum_oscillators',
			complementary_with: ['EMA_26', 'VOLUME'],
			conflicts_with: [],
		},
	},
	roc: {
		name: 'ROC',
		category: 'momentum',
		description: 'Rate of Change',
		longDescription: 'Percentage change over N periods. >0 bullish, <0 bearish. Period=12.',
		defaultConfig: { period: 12 },
		warmup: (c) => c.period || 12,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'ROC_12',
			subcategory: 'oscillator_unbounded',
			signal_type: 'trend',
			lag: 'low',
			best_for: ['trending', 'momentum_shifts'],
			correlation_group: 'momentum_rate',
			complementary_with: ['MACD_12_26_9', 'EMA_26'],
			conflicts_with: ['MOM_10'],
		},
	},
	mom: {
		name: 'Momentum',
		category: 'momentum',
		description: 'Absolute Momentum',
		longDescription: 'Current price - N bars ago. >0 positive, <0 negative. Period=10.',
		defaultConfig: { period: 10 },
		warmup: (c) => c.period || 10,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'MOM_10',
			subcategory: 'oscillator_unbounded',
			signal_type: 'trend',
			lag: 'low',
			best_for: ['trending', 'momentum_shifts'],
			correlation_group: 'momentum_rate',
			complementary_with: ['MACD_12_26_9', 'EMA_26'],
			conflicts_with: ['ROC_12'],
		},
	},

	// === Volatility ===
	atr: {
		name: 'ATR',
		category: 'volatility',
		description: 'Average True Range',
		longDescription: 'Volatility measure. High=widen stops, low=tighten. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => c.period || 14,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'ATR_14',
			subcategory: 'range_measure',
			signal_type: 'confirmation',
			lag: 'medium',
			best_for: ['trending', 'volatility_measure', 'stop_loss'],
			correlation_group: 'volatility_range',
			complementary_with: ['ADX_14', 'BB_20_2', 'PSAR'],
			conflicts_with: [],
		},
	},
	bb: {
		name: 'Bollinger Bands',
		category: 'volatility',
		description: 'Bollinger Bands',
		longDescription: 'upper/middle/lower. period=20, dev=2. Upper/Lower=±2σ, Middle=SMA.',
		defaultConfig: { period: 20, deviation: 2 },
		warmup: (c) => c.period || 20,
		type: 'composite',
		parametrable: true,
		components: ['upper', 'middle', 'lower'],
		metadata: {
			id: 'BB_20_2',
			subcategory: 'envelope',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['ranging', 'mean_reversion', 'breakout', 'overbought_oversold'],
			correlation_group: 'volatility_bands',
			complementary_with: ['RSI_14', 'VOLUME', 'BBWIDTH_20_2'],
			conflicts_with: ['ACCELERATION_BANDS_20_2'],
		},
	},
	accelerationBands: {
		name: 'Acceleration Bands',
		category: 'volatility',
		description: 'Acceleration Bands',
		longDescription: 'upper/middle/lower. Modified Bollinger. period=20, dev=2. Breakouts & mean reversion.',
		defaultConfig: { period: 20, deviation: 2 },
		warmup: (c) => c.period || 20,
		type: 'composite',
		parametrable: true,
		components: ['upper', 'middle', 'lower'],
		metadata: {
			id: 'ACCELERATION_BANDS_20_2',
			subcategory: 'envelope',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['breakout', 'mean_reversion'],
			correlation_group: 'volatility_bands',
			complementary_with: ['RSI_14', 'VOLUME'],
			conflicts_with: ['BB_20_2'],
		},
	},
	bbWidth: {
		name: 'BB Width',
		category: 'volatility',
		description: 'Bollinger Bands Width',
		longDescription: '(upper-lower)/middle. Low=squeeze (breakout coming), high=volatility. period=20, dev=2.',
		defaultConfig: { period: 20, deviation: 2 },
		warmup: (c) => c.period || 20,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'BBWIDTH_20_2',
			subcategory: 'squeeze_measure',
			signal_type: 'confirmation',
			lag: 'low',
			best_for: ['breakout', 'squeeze', 'volatility_measure'],
			correlation_group: 'volatility_compression',
			complementary_with: ['BB_20_2', 'RSI_14', 'VOLUME'],
			conflicts_with: [],
		},
	},
	iqr: {
		name: 'IQR',
		category: 'volatility',
		description: 'Interquartile Range',
		longDescription: 'Q3-Q1. Robust volatility, outlier-resistant. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => c.period || 14,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'IQR_14',
			subcategory: 'robust_measure',
			signal_type: 'confirmation',
			lag: 'medium',
			best_for: ['volatility_measure', 'outlier_detection'],
			correlation_group: 'volatility_robust',
			complementary_with: ['ATR_14'],
			conflicts_with: [],
		},
	},
	mad: {
		name: 'MAD',
		category: 'volatility',
		description: 'Median Absolute Deviation',
		longDescription: 'Robust dispersion, extreme-insensitive. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => c.period || 14,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'MAD_14',
			subcategory: 'robust_measure',
			signal_type: 'confirmation',
			lag: 'medium',
			best_for: ['volatility_measure', 'outlier_detection'],
			correlation_group: 'volatility_robust',
			complementary_with: ['ATR_14'],
			conflicts_with: [],
		},
	},

	// === Trend ===
	adx: {
		name: 'ADX',
		category: 'trend',
		description: 'Average Directional Index',
		longDescription: 'Trend strength 0-100, no direction. >25 strong, <20 range, >50 very strong. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => (c.period || 14) * 2,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'ADX_14',
			subcategory: 'strength_measure',
			signal_type: 'confirmation',
			lag: 'high',
			best_for: ['trending', 'regime_detection', 'trend_strength'],
			correlation_group: 'trend_strength',
			complementary_with: ['MACD_12_26_9', 'PSAR', 'EMA_26', 'ATR_14'],
			conflicts_with: ['DX_14'],
		},
	},
	dx: {
		name: 'DX',
		category: 'trend',
		description: 'Directional Movement Index',
		longDescription: 'ADX component, no smoothing. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => c.period || 14,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'DX_14',
			subcategory: 'directional_measure',
			signal_type: 'confirmation',
			lag: 'medium',
			best_for: ['trending', 'directional_movement'],
			correlation_group: 'trend_strength',
			complementary_with: ['MACD_12_26_9', 'EMA_26'],
			conflicts_with: ['ADX_14'],
		},
	},
	psar: {
		name: 'Parabolic SAR',
		category: 'trend',
		description: 'Parabolic Stop And Reverse',
		longDescription: 'Below price=uptrend, above=downtrend. Flip=reversal. step=0.02, max=0.2.',
		defaultConfig: { step: 0.02, max: 0.2 },
		warmup: () => 5,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'PSAR_0.02_0.2',
			subcategory: 'reversal_system',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['trending', 'stop_loss', 'reversal'],
			correlation_group: 'trend_reversal',
			complementary_with: ['ADX_14', 'ATR_14', 'MACD_12_26_9'],
			conflicts_with: [],
		},
	},
	tds: {
		name: 'TD Sequential',
		category: 'trend',
		description: 'Tom DeMark Sequential',
		longDescription: 'Counts consecutive moves. 9+=exhaustion signal.',
		defaultConfig: {},
		warmup: () => 10,
		type: 'numeric',
		parametrable: false,
		components: null,
		metadata: {
			id: 'TDS',
			subcategory: 'exhaustion_count',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['exhaustion', 'reversal'],
			correlation_group: 'trend_exhaustion',
			complementary_with: ['RSI_14', 'MACD_12_26_9'],
			conflicts_with: [],
		},
	},
	ichimoku: {
		name: 'Ichimoku',
		category: 'trend',
		description: 'Ichimoku Cloud',
		longDescription: 'tenkan/kijun/senkouA/senkouB/chikou. tenkan=9, kijun=26, senkou=52, disp=26.',
		defaultConfig: { tenkan: 9, kijun: 26, senkou: 52, displacement: 26 },
		warmup: (c) => c.senkou || 52,
		type: 'composite',
		parametrable: true,
		components: ['tenkan', 'kijun', 'senkouA', 'senkouB', 'chikou'],
		metadata: {
			id: 'ICHIMOKU_9_26_52_26',
			subcategory: 'cloud_system',
			signal_type: 'trend',
			lag: 'high',
			best_for: ['trending', 'support_resistance', 'momentum'],
			correlation_group: 'trend_cloud',
			complementary_with: ['VOLUME', 'ADX_14'],
			conflicts_with: [],
		},
	},

	// === Volume ===
	obv: {
		name: 'OBV',
		category: 'volume',
		description: 'On-Balance Volume',
		longDescription: 'Cumulative directional volume. Divergence=reversal signal.',
		defaultConfig: {},
		warmup: () => 1,
		type: 'numeric',
		parametrable: false,
		components: null,
		metadata: {
			id: 'OBV',
			subcategory: 'cumulative',
			signal_type: 'confirmation',
			lag: 'low',
			best_for: ['trending', 'divergence', 'accumulation_distribution'],
			correlation_group: 'volume_cumulative',
			complementary_with: ['MACD_12_26_9', 'RSI_14', 'EMA_26'],
			conflicts_with: [],
		},
	},
	vwap: {
		name: 'VWAP',
		category: 'volume',
		description: 'Volume Weighted Average Price',
		longDescription: 'Price>VWAP=buyers dominate. Institutional benchmark.',
		defaultConfig: {},
		warmup: () => 1,
		type: 'numeric',
		parametrable: false,
		components: null,
		metadata: {
			id: 'VWAP',
			subcategory: 'weighted_average',
			signal_type: 'trend',
			lag: 'low',
			best_for: ['intraday', 'institutional_levels', 'mean_reversion'],
			correlation_group: 'volume_price',
			complementary_with: ['RSI_14', 'EMA_26', 'VOLUME'],
			conflicts_with: [],
		},
	},

	// === Support & Resistance ===
	linearRegression: {
		name: 'Linear Regression',
		category: 'supportResistance',
		description: 'Linear Regression Trendline',
		longDescription: 'Price>line=above trend. Slope=strength. Period=14.',
		defaultConfig: { period: 14 },
		warmup: (c) => c.period || 14,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'LINEAR_REGRESSION_14',
			subcategory: 'trendline',
			signal_type: 'trend',
			lag: 'medium',
			best_for: ['trending', 'mean_reversion'],
			correlation_group: 'regression',
			complementary_with: ['RSI_14', 'BB_20_2'],
			conflicts_with: [],
		},
	},
	zigzag: {
		name: 'ZigZag',
		category: 'supportResistance',
		description: 'ZigZag',
		longDescription: 'Filters moves <threshold %. Major swings. Lagging. Def=5%.',
		defaultConfig: { threshold: 5 },
		warmup: () => 10,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'ZIGZAG_5',
			subcategory: 'swing_points',
			signal_type: 'confirmation',
			lag: 'high',
			best_for: ['swing_identification', 'pattern_recognition'],
			correlation_group: 'swing_detection',
			complementary_with: ['ICHIMOKU_9_26_52_26'],
			conflicts_with: [],
		},
	},

	// === Advanced ===
	ao: {
		name: 'Awesome Oscillator',
		category: 'advanced',
		description: 'Awesome Oscillator',
		longDescription: 'Bill Williams (SMA short-long of HL/2). >0 bullish, <0 bearish. short=5, long=34.',
		defaultConfig: { short: 5, long: 34 },
		warmup: (c) => c.long || 34,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'AO_5_34',
			subcategory: 'bill_williams',
			signal_type: 'trend',
			lag: 'medium',
			best_for: ['trending', 'momentum'],
			correlation_group: 'williams_indicators',
			complementary_with: ['AC_5_34_5', 'VOLUME'],
			conflicts_with: ['MACD_12_26_9', 'MOM_10'],
		},
	},
	ac: {
		name: 'Accelerator',
		category: 'advanced',
		description: 'Accelerator Oscillator',
		longDescription: 'Bill Williams acceleration (AO derivative). Changes before AO=early signal. short=5, long=34, signal=5.',
		defaultConfig: { short: 5, long: 34, signal: 5 },
		warmup: (c) => (c.long || 34) + (c.signal || 5),
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'AC_5_34_5',
			subcategory: 'bill_williams',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['early_reversal', 'acceleration'],
			correlation_group: 'williams_indicators',
			complementary_with: ['AO_5_34', 'VOLUME'],
			conflicts_with: [],
		},
	},
	cg: {
		name: 'Center of Gravity',
		category: 'advanced',
		description: 'Center of Gravity',
		longDescription: 'Leading indicator. Extremes=imminent reversal. Regression-based. Period=10, signal=5.',
		defaultConfig: { period: 10, signalInterval: 5 },
		warmup: (c) => (c.period || 10) + (c.signalInterval || 5),
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'CG_10',
			subcategory: 'leading_oscillator',
			signal_type: 'reversal',
			lag: 'low',
			best_for: ['reversal', 'leading_signals'],
			correlation_group: 'leading_indicators',
			complementary_with: ['RSI_14', 'MACD_12_26_9'],
			conflicts_with: [],
		},
	},
	rei: {
		name: 'Range Expansion',
		category: 'advanced',
		description: 'Range Expansion Index',
		longDescription: 'Expansion vs contraction days. High=volatility rising, breakout near. Period=10.',
		defaultConfig: { period: 10 },
		warmup: (c) => c.period || 10,
		type: 'numeric',
		parametrable: true,
		components: null,
		metadata: {
			id: 'REI_10',
			subcategory: 'expansion_measure',
			signal_type: 'confirmation',
			lag: 'low',
			best_for: ['breakout', 'expansion'],
			correlation_group: 'expansion_indicators',
			complementary_with: ['BBWIDTH_20_2', 'ATR_14'],
			conflicts_with: [],
		},
	},
	tr: {
		name: 'True Range',
		category: 'advanced',
		description: 'True Range',
		longDescription: 'Instant volatility (max high-low, gaps). ATR basis.',
		defaultConfig: {},
		warmup: () => 1,
		type: 'numeric',
		parametrable: false,
		components: null,
		metadata: {
			id: 'TR',
			subcategory: 'volatility_instant',
			signal_type: 'confirmation',
			lag: 'low',
			best_for: ['volatility_measure', 'instant_volatility'],
			correlation_group: 'volatility_range',
			complementary_with: ['ATR_14'],
			conflicts_with: [],
		},
	},
};

// Build registry from data
export const INDICATOR_REGISTRY = {};
for (const key in INDICATORS_DATA) {
	const data = INDICATORS_DATA[key];
	INDICATOR_REGISTRY[key] = {
		indicator: key,
		name: data.name,
		category: data.category,
		description: data.description,
		longDescription: data.longDescription,
		defaultConfig: data.defaultConfig,
		warmup: data.warmup,
		type: data.type,
		parametrable: data.parametrable,
		...(data.components && { components: data.components }),
		id: data.metadata.id,
		subcategory: data.metadata.subcategory,
		signal_type: data.metadata.signal_type,
		lag: data.metadata.lag,
		best_for: data.metadata.best_for,
		correlation_group: data.metadata.correlation_group,
		complementary_with: data.metadata.complementary_with,
		conflicts_with: data.metadata.conflicts_with,
	};
}

/**
 * Get metadata for a specific indicator
 * @param {string} key - Indicator key (e.g., 'sma', 'rsi', 'macd')
 * @returns {Object|null} Indicator metadata or null if not found
 */
export function getIndicatorMetadata(key) {
	return INDICATOR_REGISTRY[key] || null;
}

/**
 * Build catalog structure from indicators by category
 * @returns {Object} Catalog organized by category with indicator lists
 */
function buildCatalog() {
	const catalog = {};
	const categoryNames = {
		movingAverages: 'Moving Averages',
		momentum: 'Momentum Indicators',
		volatility: 'Volatility Indicators',
		trend: 'Trend Indicators',
		volume: 'Volume Indicators',
		supportResistance: 'Support & Resistance',
		advanced: 'Advanced',
	};

	const categoryDescriptions = {
		movingAverages: 'Trend following averages and smoothing indicators',
		momentum: 'Momentum indicators measure strength and direction',
		volatility: 'Volatility indicators measure price movement amplitude',
		trend: 'Trend indicators determine direction and strength',
		volume: 'Volume analysis confirms price movements',
		supportResistance: 'Identify potential support and resistance levels',
		advanced: 'Advanced oscillators and volatility measures',
	};

	for (const [key, metadata] of Object.entries(INDICATOR_REGISTRY)) {
		const category = metadata.category;
		if (!catalog[category])
			catalog[category] = {
				name: categoryNames[category],
				description: categoryDescriptions[category],
				indicators: [],
			};
		catalog[category].indicators.push(key);
	}

	return catalog;
}

const INDICATOR_CATALOG = buildCatalog();

/**
 * Get formatted catalog with detailed indicator information
 * @returns {Object} Formatted catalog with indicator metadata
 */
export function getFormattedCatalog() {
	const formatted = {};
	for (const [key, catalog] of Object.entries(INDICATOR_CATALOG))
		formatted[key] = {
			name: catalog.name,
			description: catalog.description,
			indicatorCount: catalog.indicators.length,
			indicators: catalog.indicators.map(indicatorKey => {
				const metadata = INDICATOR_REGISTRY[indicatorKey];
				// Calculate warmup with default config
				const warmup = typeof metadata.warmup === 'function'
					? metadata.warmup(metadata.defaultConfig)
					: metadata.warmup;

				return {
					key: indicatorKey,
					name: metadata.name,
					description: metadata.description,
					warmup: warmup,
				};
			}),
		};
	return formatted;
}

export default INDICATOR_REGISTRY;
